# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: ShopServices
      MARIADB_USER: shopuser
      MARIADB_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    ports:
      - 8090:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: 123456
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper