spring:
  application:
    name: app-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-products
          uri: http://localhost:8081/product
          predicates:
            - Path=/products/**
        - id: service-users
          uri: http://localhost:8082/user
          predicates:
            - Path=/users/**
        - id: service-orders
          uri: http://localhost:8083/order
          predicates:
            - Path=/orders/**
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true