spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-products
          uri: http://localhost:8081/api
          predicates:
            - Path=/products/**
        - id: service-users
          uri: http://localhost:8082/api
          predicates:
            - Path=/users/**
        - id: service-orders
          uri: http://localhost:8083/api
          predicates:
            - Path=/orders/**
